[package]
name = "rpi-vbus-logger"
version = "0.2.0"
authors = ["Daniel Wippermann <Daniel.Wippermann@gmail.com>"]

[dependencies]
mysql = "*"
serde = "*"
serde_derive = "*"
serial = "*"
resol-vbus = "*"
toml = "*"
